# Site Information
description: "记录成长，分享生活与技术的点滴"
keywords: "江岳勋, 江岳勋的博客, Ahonn, Ahonn's Blog, 前端，博客"
favicon: images/favicon.ico
rss: /atom.xml

# Site Menu
# Neet slash(/) at the end
menu:
  home: /
  # 技术: categories/technology/ 
  思考: categories/thinking/
  生活: categories/life/
  archives: archives/
  about: about/

# Site Sidebar Widget
widgets:
  - recent_post
  - tagcloud
  - categories
  # - archives
  - links

# Site Friend Links
links:
  yzzting: http://www.yzz1995.cn/
  co1mugx: http://blog.co1mugx.tk/
  leyar: https://www.ileyar.com/

social:
  github: https://github.com/

analytics:
  google: UA-74273646-1
  baidu: 0a275bcf7d954b807e1db498d8e5b192

# Site Verification
verification:
  baidu: 0a275bcf7d954b807e1db498d8e5b192
  google: j5dWC85DkoAfUR50W00ewfii3X9ouH55HnyBP6oZxGE

comment:
  disqus: ahonn
